apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: express-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app 
    spec:
      containers:
      - name: express-app
        image: haiqal47/express-app:latest
        ports:
        - containerPort: 3000
